# Generated by Django 5.0.3 on 2024-04-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_username', models.CharField(max_length=200, null=True)),
                ('admin_comment', models.CharField(max_length=2000, null=True)),
                ('file_url', models.CharField(max_length=300, null=True)),
                ('file_name', models.CharField(max_length=300, null=True)),
                ('report_text', models.CharField(max_length=2000)),
                ('organization_name', models.CharField(max_length=300)),
                ('report_name', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='New', max_length=300)),
                ('report_type', models.CharField(choices=[('P', 'Air or water pollution'), ('E', 'Excessive energy usage'), ('W', 'Excessive waste'), ('R', 'Use of unsustainable resources'), ('N', 'Destruction of nature'), ('S', 'Harmful supply chains'), ('O', 'Other')], default='O', max_length=2)),
            ],
        ),
    ]
